[tool.poetry]
name = "fastapi-base"
version = "0.1.0"
description = ""
authors = ["Abe M <abe.malla8@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
redis = "^5.0.0"
boto3 = "^1.28.26"
uvicorn = "^0.23.2"
pydantic = "^2.1.1"
alembic = "^1.11.2"
python-dotenv = "^1.0.0"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
pymysql = "^1.1.0"
orjson = "^3.9.4"
psycopg = "^3.1.10"
sqlalchemy = "^2.0.19"
prometheus-fastapi-instrumentator = "^6.1.0"
gunicorn = "^21.2.0"
pydantic-settings = "^2.0.3"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.2"
mypy = "^1.2.0"
types-redis = "^4.5.4.1"
ruff = "^0.0.264"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 100
target-version = "py311"
extend-exclude = [".pytest_cache"]
ignore-init-module-imports = true

[tool.ruff.mccabe]
max-complexity = 10

[tool.ruff.per-file-ignores]
"main.py" = ["E402"]
"shell.py" = ["F401"]
